=== salineroalex/ProjectUnmatched/public_html/back/xsd/schema_sets.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema version="1.0"
            xmlns="../xml/sets.xml"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    
    <!--Here is the data structure for the SETS node-->
    <xsd:element name="sets">
        <xsd:complexType>
            
            <xsd:sequence>
                <xsd:element name="set" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="numbCharacters" type="xsd:positiveInteger"/>
                            <xsd:element name="price" type="xsd:decimal"/>
                            <xsd:element name="date" type="xsd:string"/>
                            <xsd:element name="language" type="xsd:string"/>
                            <xsd:element name="artist" type="xsd:string"/>
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:string" use="required"/>
                        <xsd:attribute name="released" type="xsd:boolean" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            
        </xsd:complexType>
    </xsd:element>
    
    
</xsd:schema>

=== salineroalex/ProjectUnmatched/public_html/back/xml/sets.xml
<?xml version="1.0" encoding="UTF-8"?>

<sets 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation = "../xsd/schema_sets.xsd">
    
    <set id="BL1" released="true">
        <name>Battle of Legends: Volumen One</name>
        <numbCharacters>4</numbCharacters>
        <price>34.15</price>
        <date>09/2019</date>
        <language>Spanish</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="RHB" released="true">
        <name>Robin Hood vs. Bigfoot</name>
        <numbCharacters>2</numbCharacters>
        <price>25.15</price>
        <date>10/2019</date>
        <language>Spanish</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="LEE" released="true">
        <name>Bruce Lee</name>
        <numbCharacters>1</numbCharacters>
        <price>14.36</price>
        <date>10/2019</date>
        <language>English</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="IGR" released="true">
        <name>Jurassic Park: InGen vs. Raptors</name>
        <numbCharacters>2</numbCharacters>
        <price>25.15</price>
        <date>04/2020</date>
        <language>English</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="CNF" released="true">
        <name>Cobble &#38; Fog</name>
        <numbCharacters>4</numbCharacters>
        <price>34.15</price>
        <date>07/2020</date>
        <language>Spanish</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="BVS" released="true">
        <name>Buffy the Vampire Slayer</name>
        <numbCharacters>4</numbCharacters>
        <price>34.15</price>
        <date>10/2020</date>
        <language>English</language>
        <artist>Heather Vaughan</artist>
    </set>
    
    <set id="LRB" released="true">
        <name>Little Red Riding hood vs. Beowulf</name>
        <numbCharacters>2</numbCharacters>
        <price>25.15</price>
        <date>12/2020</date>
        <language>English</language>
        <artist>Marc Aspinall</artist>
    </set>
    
    <set id="DPL" released="true">
        <name>Deadpool</name>
        <numbCharacters>1</numbCharacters>
        <price>14.36</price>
        <date>07/2021</date>
        <language>English</language>
        <artist>Heather Vaughan</artist>
    </set>
    
    <set id="BL2" released="true">
        <name>Battle of Legends: Volume Two</name>
        <numbCharacters>4</numbCharacters>
        <price>34.15</price>
        <date>01/2022</date>
        <language>English</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="MRR" released="true">
        <name>Marvel's Redemption Row</name>
        <numbCharacters>3</numbCharacters>
        <price>44.95</price>
        <date>04/2022</date>
        <language>English</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="MHK" released="true">
        <name>Marvel's Hell Kitchen</name>
        <numbCharacters>3</numbCharacters>
        <price>44.95</price>
        <date>04/2022</date>
        <language>English</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="STR" released="true">
        <name>Jurassic Park: Dr. Ellie Sattler vs. T-Rex</name>
        <numbCharacters>2</numbCharacters>
        <price>25.15</price>
        <date>05/2022</date>
        <language>English</language>
        <artist>Oliver Barrett</artist>
    </set>
    
    <set id="HVG" released="true">
        <name>Houdini vs. Genie</name>
        <numbCharacters>2</numbCharacters>
        <price>25.15</price>
        <date>12/2022</date>
        <language>English</language>
        <artist>Peter Diamond</artist>
    </set>

    <set id="MTS" released="false">
        <name>Marvel's Teen Spirit</name>
        <numbCharacters>3</numbCharacters>
        <price>44.95</price>
        <date>04/2023</date>
        <language>English</language>
        <artist>Heather Vaughan</artist>
    </set>
    
    <set id="MKC" released="false">
        <name>Marvel's For King and Country</name>
        <numbCharacters>3</numbCharacters>
        <price>44.95</price>
        <date>04/2023</date>
        <language>English</language>
        <artist>Heather Vaughan</artist>
    </set>

</sets>
